name: zdoom-git # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Doom engine with advanced moding features (git version). # 79 char long summary
description: |
  ZDoom is a source port, originally based off ATB Doom and NTDoom. It has since added practically full support for Boom, Chex Quest, Heretic, Hexen and Strife; and several games have been developed specifically for it. It has added many additional features, including slopes, uncapped fps and z-clipping. The source code is maintained by Randy Heit and Graf Zahl.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
	zdoom-git:
		command: zdoom

parts:
	zdoom-scr: # See 'snapcraft plugins'
		plugin: cmake
			source: https://github.com/rheit/zdoom.git
			source-type: git
